interfaces:
  - dev: enp2s0
    addresses:
      - "fd00:4::5/64"
  - dev: enp3s0
    addresses:
      - "10.5.0.5/24"

sysctl_params:
  net.ipv4.ip_forward: "1"
  net.ipv6.conf.all.forwarding: "1"
  net.ipv6.conf.all.seg6_enabled: "1"
  net.ipv6.conf.enp2s0.seg6_enabled: "1"

ipv6_routes:
  - dest: "fd00:a:2::/48"
    via: "fd00:4::4"
    dev: enp2s0
  - dest: "fd00:a:3::/48"
    via: "fd00:4::4"
    dev: enp2s0
  - dest: "fd00:a:4::/48"
    via: "fd00:4::4"
    dev: enp2s0
  - dest: "fd00:a:7::/48"
    via: "fd00:4::4"
    dev: enp2s0

srv6_local_sids:
  - sid: "fd00:a:5::d4"
    nh4: "10.5.0.6"
    dev: enp3s0

srv6_encap_routes:
  - dest: "10.1.0.0/24"
    segs: "fd00:a:2::d4"
    dev: enp2s0
